// Tanmoyeen Masr - Active Opportunities cumulative file
// Current through 1 October 2026
window.TANMOYEEN_BULK_JOBS = [
  {
    "title": "Senior Program Officer – Refugee and Migrant Rights",
    "org": "المبادرة المصرية للحقوق الشخصية – EIPR",
    "gov": "القاهرة",
    "type": "دوام كامل",
    "sec": "حقوق الإنسان والحماية",
    "sal": "",
    "dl": "2026-10-08",
    "contact": "jobs@eipr.org",
    "desc": "برنامج حقوق اللاجئين والمهاجرين؛ بحث وسياسات ومناصرة ومساعدة قانونية.",
    "link": "https://eg.linkedin.com/jobs/view/vacancy-senior-program-officer-on-refugee-and-migrant-rights-at-egyptian-initiative-for-personal-rights-eipr-4470963894",
    "source": "EIPR"
  },
  {
    "title": "22 معلم/ة – 11 مدرسة مجتمعية",
    "org": "جمعية الطفولة والتنمية بأسيوط – ACDA",
    "gov": "مطروح",
    "type": "دوام كامل",
    "sec": "التعليم والتنمية",
    "sal": "",
    "dl": "2026-10-05",
    "contact": "jobs@acdaegypt.com",
    "desc": "22 معلما ومعلمة للعمل في 11 مدرسة مجتمعية ضمن Schools for Egypt 4.",
    "link": "https://lnkd.in/eVmCbF-H",
    "source": "ACDA"
  },
  {
    "title": "Administrative & Operations Manager",
    "org": "جمعية كيان للأشخاص ذوي الإعاقة",
    "gov": "القاهرة",
    "type": "دوام كامل",
    "sec": "الإدارة والتشغيل",
    "sal": "",
    "dl": "2026-10-06",
    "contact": "",
    "desc": "إدارة العمليات والشؤون الإدارية والفرق، مع أفضلية لخبرة المجتمع المدني والتنمية.",
    "link": "https://www.kaianegypt.com/index.php/careers",
    "source": "Kayan Egypt"
  },
  {
    "title": "Program Administrative Assistant",
    "org": "جمعية خير وبركة والمرأة الجديدة",
    "gov": "الأسمرات",
    "type": "دوام كامل",
    "sec": "الإدارة والبرامج",
    "sal": "",
    "dl": "2026-10-08",
    "contact": "",
    "desc": "مساعد إداري للبرامج.",
    "link": "https://bit.ly/4rDu6Le",
    "source": "Khayr wa Baraka & New Woman Association"
  },
  {
    "title": "Program Manager – Health & Safety / IPPF",
    "org": "جمعية خير وبركة والمرأة الجديدة",
    "gov": "الأسمرات",
    "type": "دوام كامل",
    "sec": "إدارة البرامج والصحة",
    "sal": "",
    "dl": "2026-10-08",
    "contact": "",
    "desc": "مدير برنامج للصحة والسلامة ضمن IPPF.",
    "link": "https://bit.ly/4yoqmzV",
    "source": "Khayr wa Baraka & New Woman Association"
  },
  {
    "title": "Business Development Sector",
    "org": "جمعية خير وبركة والمرأة الجديدة",
    "gov": "القاهرة",
    "type": "دوام كامل",
    "sec": "تطوير الأعمال",
    "sal": "",
    "dl": "2026-10-04",
    "contact": "",
    "desc": "فرصة ضمن قطاع تطوير الأعمال.",
    "link": "https://bit.ly/4jrNKaT",
    "source": "Khayr wa Baraka & New Woman Association"
  },
  {
    "title": "Social Media Specialist",
    "org": "Mersal",
    "gov": "المعادي – القاهرة",
    "type": "دوام كامل",
    "sec": "الإعلام والتواصل",
    "sal": "",
    "dl": "",
    "contact": "",
    "desc": "Social Media Specialist – Full Time / Hybrid.",
    "link": "https://wuzzuf.net/jobs/careers/Mersal-Egypt-45113",
    "source": "Wuzzuf / Mersal"
  },
  {
    "title": "Project Manager",
    "org": "مكتب التنمية الإيبارشي بالإسماعيلية – IDDO",
    "gov": "الإسماعيلية",
    "type": "دوام كامل",
    "sec": "إدارة المشاريع",
    "sal": "",
    "dl": "",
    "contact": "",
    "desc": "Project Manager – الإعلان حديث، وموعد الإغلاق غير ظاهر في المصدر المفهرس.",
    "link": "https://www.jobs-arab.com/eg/job-location/%D8%A7%D9%84%D8%A7%D8%B3%D9%85%D8%A7%D8%B9%D9%8A%D9%84%D9%8A%D9%87/",
    "source": "Jobs-Arab / IDDO"
  },
  {
    "title": "Accountant",
    "org": "مكتب التنمية الإيبارشي بالإسماعيلية – IDDO",
    "gov": "الإسماعيلية",
    "type": "دوام كامل",
    "sec": "الإدارة المالية",
    "sal": "",
    "dl": "",
    "contact": "",
    "desc": "Accountant – الإعلان حديث، وموعد الإغلاق غير ظاهر في المصدر المفهرس.",
    "link": "https://www.jobs-arab.com/eg/job-profession/%D9%85%D8%A7%D9%84-%D9%88%D9%85%D8%AD%D8%A7%D8%B3%D8%A8%D9%87/job-location/%D8%A7%D9%84%D8%A7%D8%B3%D9%85%D8%A7%D8%B9%D9%8A%D9%84%D9%8A%D9%87/",
    "source": "Jobs-Arab / IDDO"
  },
  {
    "title": "Director of Psychosocial Department",
    "org": "StARS",
    "gov": "القاهرة",
    "type": "دوام كامل",
    "sec": "الدعم النفسي والاجتماعي",
    "sal": "",
    "dl": "2026-10-03",
    "contact": "applications@stars-egypt.org",
    "desc": "مدير إدارة الدعم النفسي والاجتماعي.",
    "link": "https://stars-egypt.org/",
    "source": "StARS"
  },
  {
    "title": "Senior Public Relations Specialist",
    "org": "مؤسسة حياة كريمة",
    "gov": "القاهرة الجديدة",
    "type": "دوام كامل",
    "sec": "العلاقات العامة والاتصال",
    "sal": "",
    "dl": "2026-10-01",
    "contact": "",
    "desc": "علاقات عامة واتصالات خارجية مع زيارات ميدانية محتملة.",
    "link": "https://lnkd.in/ejSZ8i2k",
    "source": "Haya Karima Foundation"
  },
  {
    "title": "Senior CSR Specialist",
    "org": "مؤسسة حياة كريمة",
    "gov": "القاهرة الجديدة",
    "type": "دوام كامل",
    "sec": "المسؤولية المجتمعية والشراكات",
    "sal": "",
    "dl": "2026-10-01",
    "contact": "",
    "desc": "إدارة مبادرات المسؤولية المجتمعية والشراكات.",
    "link": "https://lnkd.in/eKmaF2ej",
    "source": "Haya Karima Foundation"
  },
  {
    "title": "Content & Digital Communications Senior Specialist",
    "org": "مؤسسة حياة كريمة",
    "gov": "القاهرة الجديدة",
    "type": "دوام كامل",
    "sec": "الإعلام والاتصال الرقمي",
    "sal": "",
    "dl": "2026-10-01",
    "contact": "",
    "desc": "المحتوى والاتصالات الرقمية وإدارة الحملات والمحتوى.",
    "link": "https://lnkd.in/eagS3in8",
    "source": "Haya Karima Foundation"
  },
  {
    "title": "Business Development Specialist",
    "org": "مؤسسة حياة كريمة",
    "gov": "القاهرة الجديدة",
    "type": "دوام كامل",
    "sec": "تطوير الأعمال والشراكات",
    "sal": "",
    "dl": "2026-10-01",
    "contact": "",
    "desc": "تطوير فرص وشراكات وتمويلات استراتيجية.",
    "link": "https://lnkd.in/ePMn7FYg",
    "source": "Haya Karima Foundation"
  },
  {
    "title": "MEAL Officer",
    "org": "مؤسسة حياة كريمة",
    "gov": "القاهرة الجديدة",
    "type": "دوام كامل",
    "sec": "المتابعة والتقييم والمساءلة والتعلم",
    "sal": "",
    "dl": "2026-10-01",
    "contact": "",
    "desc": "دعم أنظمة المتابعة وجودة البيانات وقياس الأداء.",
    "link": "https://lnkd.in/ey_6AhUJ",
    "source": "Haya Karima Foundation"
  },
  {
    "title": "Supply Chain Manager",
    "org": "مؤسسة حياة كريمة",
    "gov": "القاهرة الجديدة",
    "type": "دوام كامل",
    "sec": "المشتريات وسلاسل الإمداد",
    "sal": "",
    "dl": "2026-10-01",
    "contact": "",
    "desc": "إدارة المشتريات واللوجستيات والمخزون وسلاسل الإمداد.",
    "link": "https://lnkd.in/eSm9yF5m",
    "source": "Haya Karima Foundation"
  },
  {
    "title": "Project Officer – Livelihoods Program",
    "org": "Catholic Relief Services – CRS",
    "gov": "القاهرة + سفر إلى أسيوط",
    "type": "دوام كامل",
    "sec": "سبل العيش والتنمية الاقتصادية",
    "sal": "",
    "dl": "2026-10-10",
    "contact": "",
    "desc": "وظيفتان، عقد 12 شهرا حسب التمويل، وسفر ميداني إلى أسيوط.",
    "link": "https://crsegyptjobs.crs.org/job.php?id=992507",
    "source": "CRS"
  },
  {
    "title": "Volunteers",
    "org": "Catholic Relief Services – CRS",
    "gov": "القاهرة",
    "type": "تطوع",
    "sec": "التنمية والمجتمع المدني",
    "sal": "تطوع",
    "dl": "2026-10-17",
    "contact": "",
    "desc": "فرصة تطوع لمدة تصل إلى 5 أشهر حسب المشروع.",
    "link": "https://crsegyptjobs.crs.org/",
    "source": "CRS"
  },
  {
    "title": "Country Director – Egypt",
    "org": "Terre des hommes – Tdh",
    "gov": "القاهرة",
    "type": "دوام كامل",
    "sec": "الإدارة العليا وإدارة البرامج",
    "sal": "",
    "dl": "",
    "contact": "",
    "desc": "بداية 15 أكتوبر 2026، مدة 24 شهرا، والتوظيف مستمر حتى شغل الوظيفة.",
    "link": "https://jobs.tdh.org/en-GB/jobs/8369397-country-director-egypt",
    "source": "Tdh"
  },
  {
    "title": "Child Protection Technical Advisor",
    "org": "Save the Children International",
    "gov": "القاهرة الكبرى + سفر للمحافظات",
    "type": "دوام كامل",
    "sec": "حماية الطفل",
    "sal": "",
    "dl": "2026-10-15",
    "contact": "",
    "desc": "Technical Advisor ضمن Program Development, Quality and Impact.",
    "link": "https://www.savethechildren.net/careers/apply/details?jid=15996",
    "source": "Save the Children"
  },
  {
    "title": "Case Worker – UNHCR",
    "org": "Save the Children International",
    "gov": "أسوان",
    "type": "دوام كامل",
    "sec": "الحماية وإدارة الحالات",
    "sal": "",
    "dl": "2026-10-08",
    "contact": "",
    "desc": "Case Worker ضمن مشروع UNHCR في أسوان.",
    "link": "https://joby.ps/",
    "source": "Save the Children"
  },
  {
    "title": "SGBV Senior Officer",
    "org": "Save the Children International",
    "gov": "أسوان / القاهرة",
    "type": "دوام كامل",
    "sec": "الحماية والعنف القائم على النوع الاجتماعي",
    "sal": "",
    "dl": "2026-10-01",
    "contact": "",
    "desc": "وظيفتان؛ أولوية التوظيف لدور أسوان.",
    "link": "https://www.savethechildren.net/careers/apply/details?jid=16039",
    "source": "Save the Children"
  },
  {
    "title": "Health Services Coordinator – Aswan",
    "org": "Save the Children International",
    "gov": "أسوان",
    "type": "دوام كامل",
    "sec": "الصحة",
    "sal": "",
    "dl": "2026-10-01",
    "contact": "",
    "desc": "تنسيق خدمات العيادات المتنقلة وخدمات الرعاية الصحية الأولية.",
    "link": "https://www.savethechildren.net/careers/apply/details?jid=16947",
    "source": "Save the Children"
  },
  {
    "title": "HR Officer, Legal and Policy",
    "org": "World Health Organization – WHO",
    "gov": "القاهرة",
    "type": "دوام كامل",
    "sec": "الموارد البشرية",
    "sal": "",
    "dl": "2026-10-06",
    "contact": "",
    "desc": "P4، عقد سنة مع إمكانية التمديد حسب التمويل والحاجة.",
    "link": "https://careers.who.int/careersection/ex/jobdetail.ftl?job=2603971",
    "source": "WHO"
  },
  {
    "title": "Technical Officer – Laboratory",
    "org": "World Health Organization – WHO",
    "gov": "القاهرة",
    "type": "دوام كامل",
    "sec": "الصحة والمختبرات",
    "sal": "",
    "dl": "2026-10-08",
    "contact": "",
    "desc": "P4، دعم أنظمة المختبرات والصحة العامة وبناء القدرات.",
    "link": "https://www.impactpool.org/jobs/1237561",
    "source": "WHO"
  },
  {
    "title": "Technical Officer",
    "org": "World Health Organization – WHO",
    "gov": "القاهرة",
    "type": "دوام كامل",
    "sec": "الصحة وإدارة البرامج",
    "sal": "",
    "dl": "2026-10-19",
    "contact": "",
    "desc": "P3، مكتب المدير الإقليمي، عقد سنة خاضع للتمويل والأداء والحاجة.",
    "link": "https://careers.who.int/careersection/ex/jobdetail.ftl?job=2604217",
    "source": "WHO"
  },
  {
    "title": "Consultant – Environmental Health (WASH)",
    "org": "World Health Organization – WHO",
    "gov": "القاهرة",
    "type": "استشاري",
    "sec": "المياه والصرف الصحي والصحة البيئية",
    "sal": "",
    "dl": "2026-10-05",
    "contact": "",
    "desc": "استشاري لمدة 6 أشهر لدعم WASH والصحة البيئية.",
    "link": "https://careers.who.int/careersection/ex/jobdetail.ftl?job=2604014",
    "source": "WHO"
  },
  {
    "title": "Finance Assistant – G5",
    "org": "UNFPA",
    "gov": "القاهرة – ASRO",
    "type": "دوام كامل",
    "sec": "المالية",
    "sal": "",
    "dl": "2026-10-03",
    "contact": "",
    "desc": "Finance Assistant، مستوى G5، عقد Fixed Term Appointment.",
    "link": "https://www.unfpa.org/jobs/finance-assistant-cairo-asro-g5-fta",
    "source": "UNFPA"
  },
  {
    "title": "Operational Risk and Control Specialist – P3",
    "org": "UNFPA",
    "gov": "القاهرة – ASRO",
    "type": "دوام كامل",
    "sec": "المخاطر والرقابة",
    "sal": "",
    "dl": "2026-10-05",
    "contact": "",
    "desc": "متخصص مخاطر وضوابط تشغيلية – P3.",
    "link": "https://www.impactpool.org/jobs/1237792",
    "source": "UNFPA"
  },
  {
    "title": "Strategic Advocacy Advisor – P5",
    "org": "UNFPA",
    "gov": "القاهرة – المكتب الإقليمي للدول العربية",
    "type": "دوام كامل",
    "sec": "المناصرة والاتصال",
    "sal": "",
    "dl": "2026-10-07",
    "contact": "",
    "desc": "مستشار أول للمناصرة الاستراتيجية – P5.",
    "link": "https://www.impactpool.org/jobs/1238124",
    "source": "UNFPA"
  },
  {
    "title": "Strategic Partnerships and Innovative Financing Advisor – P5",
    "org": "UNFPA",
    "gov": "القاهرة – المكتب الإقليمي للدول العربية",
    "type": "دوام كامل",
    "sec": "الشراكات والتمويل",
    "sal": "",
    "dl": "2026-10-07",
    "contact": "",
    "desc": "مستشار الشراكات الاستراتيجية والتمويل المبتكر – P5.",
    "link": "https://www.impactpool.org/jobs/1238125",
    "source": "UNFPA"
  },
  {
    "title": "Associate RSD Officer – P2",
    "org": "UNHCR",
    "gov": "القاهرة",
    "type": "دوام كامل",
    "sec": "الحماية وحقوق اللاجئين",
    "sal": "",
    "dl": "2026-10-25",
    "contact": "",
    "desc": "دعم تحديد وضع اللاجئين والشؤون القانونية والإجرائية.",
    "link": "https://www.impactpool.org/jobs/1238801",
    "source": "UNHCR"
  },
  {
    "title": "Migration Health Nurse",
    "org": "IOM",
    "gov": "القاهرة",
    "type": "دوام كامل",
    "sec": "الصحة والهجرة",
    "sal": "",
    "dl": "2026-10-01",
    "contact": "",
    "desc": "ممرض/ة صحة مهاجرين.",
    "link": "https://iom.impactpool.org/vacancies/1237160",
    "source": "IOM"
  },
  {
    "title": "Migration Health Physician",
    "org": "IOM",
    "gov": "القاهرة",
    "type": "دوام كامل",
    "sec": "الصحة والهجرة",
    "sal": "",
    "dl": "2026-10-01",
    "contact": "",
    "desc": "طبيب/ة صحة مهاجرين.",
    "link": "https://unatlas.org/job/iom/22735",
    "source": "IOM"
  },
  {
    "title": "Lab Assistant",
    "org": "IOM",
    "gov": "القاهرة",
    "type": "دوام كامل",
    "sec": "المختبرات والصحة",
    "sal": "",
    "dl": "2026-10-01",
    "contact": "",
    "desc": "مساعد/ة مختبر ضمن برنامج صحة المهاجرين.",
    "link": "https://unatlas.org/job/iom/22774",
    "source": "IOM"
  },
  {
    "title": "Information Technology Assistant – G5",
    "org": "FAO",
    "gov": "القاهرة",
    "type": "دوام كامل",
    "sec": "تكنولوجيا المعلومات",
    "sal": "",
    "dl": "2026-10-02",
    "contact": "",
    "desc": "IT Assistant – G5.",
    "link": "https://jobs.fao.org/careersection/fao_external/jobdetail.ftl?job=2601966",
    "source": "FAO"
  },
  {
    "title": "Corporate Services Coordinator",
    "org": "British Embassy Cairo",
    "gov": "القاهرة",
    "type": "دوام كامل",
    "sec": "الخدمات المؤسسية والإدارة",
    "sal": "",
    "dl": "2026-10-04",
    "contact": "",
    "desc": "Corporate Services Coordinator – Cairo.",
    "link": "https://fco.tal.net/candidate/jobboard/vacancy/1/adv/",
    "source": "British Embassy Cairo"
  }
];
