window.TANMOYEEN_BULK_JOBS = [
  {
    title: "مدير/ة الشؤون الإدارية والتشغيل – قطاع القاهرة",
    org: "جمعية كيان للأشخاص ذوي الإعاقة",
    gov: "القاهرة",
    type: "دوام كامل",
    sec: "الإدارة والتشغيل",
    sal: "يحدد لاحقا",
    dl: "2026-10-06",
    contact: "",
    desc: "إدارة وتشغيل مكاتب الجمعية بقطاع القاهرة، مع مسؤوليات إدارية وتشغيلية وقيادة فرق العمل.",
    link: "https://www.kaianegypt.com/index.php/careers",
    source: "Kayan Egypt"
  },
  {
    title: "Program Administrative Assistant",
    org: "جمعية خير وبركة والمرأة الجديدة",
    gov: "الأسمرات",
    type: "دوام كامل",
    sec: "الإدارة والبرامج",
    sal: "يحدد لاحقا",
    dl: "2026-10-08",
    contact: "",
    desc: "Program Administrative Assistant – الأسمرات.",
    link: "https://bit.ly/4rDu6Le",
    source: "Khayr wa Baraka & New Woman Association"
  },
  {
    title: "Program Manager – Health & Safety / IPPF",
    org: "جمعية خير وبركة والمرأة الجديدة",
    gov: "الأسمرات",
    type: "دوام كامل",
    sec: "إدارة البرامج والصحة",
    sal: "يحدد لاحقا",
    dl: "2026-10-08",
    contact: "",
    desc: "Program Manager – Health & Safety / IPPF – الأسمرات.",
    link: "https://bit.ly/4yoqmzV",
    source: "Khayr wa Baraka & New Woman Association"
  },
  {
    title: "Business Development Sector",
    org: "جمعية خير وبركة والمرأة الجديدة",
    gov: "القاهرة",
    type: "دوام كامل",
    sec: "تطوير الأعمال",
    sal: "يحدد لاحقا",
    dl: "2026-10-04",
    contact: "",
    desc: "فرصة ضمن قطاع تطوير الأعمال.",
    link: "https://bit.ly/4jrNKaT",
    source: "Khayr wa Baraka & New Woman Association"
  },
  {
    title: "22 معلم/ة – 11 مدرسة مجتمعية",
    org: "جمعية الطفولة والتنمية بأسيوط – ACDA",
    gov: "مطروح",
    type: "دوام كامل",
    sec: "التعليم والتنمية",
    sal: "يحدد لاحقا",
    dl: "2026-10-05",
    contact: "jobs@acdaegypt.com",
    desc: "مطلوب 22 معلما ومعلمة للعمل في 11 مدرسة مجتمعية ضمن مشروع Schools for Egypt 4 بمحافظة مطروح.",
    link: "https://lnkd.in/eVmCbF-H",
    source: "ACDA"
  },
  {
    title: "Senior Program Officer – Refugee and Migrant Rights",
    org: "المبادرة المصرية للحقوق الشخصية – EIPR",
    gov: "القاهرة",
    type: "دوام كامل",
    sec: "حقوق الإنسان والحماية",
    sal: "يحدد لاحقا",
    dl: "2026-10-08",
    contact: "jobs@eipr.org",
    desc: "Senior Program Officer on Refugee and Migrant Rights.",
    link: "https://eg.linkedin.com/jobs/view/vacancy-senior-program-officer-on-refugee-and-migrant-rights-at-egyptian-initiative-for-personal-rights-eipr-4470963894",
    source: "EIPR / LinkedIn"
  },
  {
    title: "Social Media Specialist",
    org: "Mersal",
    gov: "المعادي – القاهرة",
    type: "دوام كامل",
    sec: "الإعلام والتواصل",
    sal: "يحدد لاحقا",
    dl: "",
    contact: "",
    desc: "Social Media Specialist – Full Time / Hybrid.",
    link: "https://wuzzuf.net/jobs/careers/Mersal-Egypt-45113",
    source: "Wuzzuf / Mersal"
  },
  {
    title: "Project Manager",
    org: "مكتب التنمية الإيبارشي بالإسماعيلية – IDDO",
    gov: "الإسماعيلية",
    type: "دوام كامل",
    sec: "إدارة المشاريع",
    sal: "يحدد لاحقا",
    dl: "",
    contact: "",
    desc: "Project Manager – موعد الإغلاق غير ظاهر في المصدر الذي تم التحقق منه.",
    link: "https://www.jobs-arab.com/eg/job-location/%D8%A7%D9%84%D8%A7%D8%B3%D9%85%D8%A7%D8%B9%D9%8A%D9%84%D9%8A%D9%87/",
    source: "Jobs-Arab / IDDO"
  },
  {
    title: "Accountant",
    org: "مكتب التنمية الإيبارشي بالإسماعيلية – IDDO",
    gov: "الإسماعيلية",
    type: "دوام كامل",
    sec: "الإدارة المالية",
    sal: "يحدد لاحقا",
    dl: "",
    contact: "",
    desc: "Accountant – موعد الإغلاق غير ظاهر في المصدر الذي تم التحقق منه.",
    link: "https://www.jobs-arab.com/eg/job-profession/%D9%85%D8%A7%D9%84-%D9%88%D9%85%D8%AD%D8%A7%D8%B3%D8%A8%D9%87/job-location/%D8%A7%D9%84%D8%A7%D8%B3%D9%85%D8%A7%D8%B9%D9%8A%D9%84%D9%8A%D9%87/",
    source: "Jobs-Arab / IDDO"
  },
  {
    title: "Project Officer – Livelihoods Program",
    org: "Catholic Relief Services – CRS",
    gov: "القاهرة + سفر إلى أسيوط",
    type: "دوام كامل",
    sec: "سبل العيش والتنمية الاقتصادية",
    sal: "يحدد لاحقا",
    dl: "2026-10-10",
    contact: "",
    desc: "شاغر واحد، عقد 12 شهرا contingent on funding، خبرة 3 سنوات، والسفر إلى أسيوط حوالي 60%.",
    link: "https://crsegyptjobs.crs.org/job.php?id=992507",
    source: "CRS"
  },
  {
    title: "Volunteers",
    org: "Catholic Relief Services – CRS",
    gov: "القاهرة",
    type: "تطوع",
    sec: "التنمية والمجتمع المدني",
    sal: "تطوع",
    dl: "2026-10-17",
    contact: "",
    desc: "فرصة تطوع في القاهرة، لمدة تصل إلى 5 أشهر حسب المشروع.",
    link: "https://crsegyptjobs.crs.org/",
    source: "CRS"
  },
  {
    title: "Project Officer",
    org: "Terre des hommes – Tdh",
    gov: "القاهرة الكبرى",
    type: "دوام كامل",
    sec: "إدارة المشاريع",
    sal: "يحدد لاحقا",
    dl: "2026-10-05",
    contact: "",
    desc: "عقد 3 أشهر قابل للتجديد. الإعلان تم رصده عبر LinkedIn.",
    link: "https://eg.linkedin.com/in/belal-khaled-1203613b",
    source: "LinkedIn / Tdh"
  },
  {
    title: "Program Associate – Climate, Peace & Development",
    org: "CCCPA",
    gov: "القاهرة",
    type: "دوام كامل",
    sec: "المناخ والسلام والتنمية",
    sal: "يحدد لاحقا",
    dl: "2026-10-03",
    contact: "applications@cccpa-eg.org",
    desc: "متاحة للمصريين، خبرة 3–5 سنوات، وماجستير في مجال ذي صلة، مع إجادة العربية والإنجليزية.",
    link: "https://lnkd.in/ea8DH-HC",
    source: "CCCPA"
  }
];
