// Tanmoyeen Masr - Active Opportunities cumulative file
// Current through 4 October 2026. Replace this file only; keep filename and variable unchanged.
window.TANMOYEEN_BULK_JOBS = [
  {
    "title": "Senior Program Officer – Refugee and Migrant Rights",
    "org": "المبادرة المصرية للحقوق الشخصية – EIPR",
    "gov": "القاهرة",
    "type": "دوام كامل",
    "sec": "حقوق الإنسان والحماية",
    "sal": "",
    "dl": "2026-10-08",
    "contact": "jobs@eipr.org",
    "desc": "برنامج حقوق اللاجئين والمهاجرين؛ بحث وسياسات ومناصرة ومساعدة قانونية.",
    "link": "https://eg.linkedin.com/jobs/view/vacancy-senior-program-officer-on-refugee-and-migrant-rights-at-egyptian-initiative-for-personal-rights-eipr-4470963894",
    "source": "EIPR"
  },
  {
    "title": "22 معلم/ة – 11 مدرسة مجتمعية",
    "org": "جمعية الطفولة والتنمية بأسيوط – ACDA",
    "gov": "مطروح",
    "type": "دوام كامل",
    "sec": "التعليم والتنمية",
    "sal": "",
    "dl": "2026-10-05",
    "contact": "jobs@acdaegypt.com",
    "desc": "22 معلما ومعلمة للعمل في 11 مدرسة مجتمعية ضمن Schools for Egypt 4.",
    "link": "https://lnkd.in/eVmCbF-H",
    "source": "ACDA"
  },
  {
    "title": "Administrative & Operations Manager",
    "org": "جمعية كيان للأشخاص ذوي الإعاقة",
    "gov": "القاهرة",
    "type": "دوام كامل",
    "sec": "الإدارة والتشغيل",
    "sal": "",
    "dl": "2026-10-06",
    "contact": "",
    "desc": "إدارة العمليات والشؤون الإدارية والفرق، مع أفضلية لخبرة المجتمع المدني والتنمية.",
    "link": "https://www.kaianegypt.com/index.php/careers",
    "source": "Kayan Egypt"
  },
  {
    "title": "Program Administrative Assistant",
    "org": "جمعية خير وبركة والمرأة الجديدة",
    "gov": "الأسمرات",
    "type": "دوام كامل",
    "sec": "الإدارة والبرامج",
    "sal": "",
    "dl": "2026-10-08",
    "contact": "",
    "desc": "مساعد إداري للبرامج.",
    "link": "https://bit.ly/4rDu6Le",
    "source": "Khayr wa Baraka & New Woman Association"
  },
  {
    "title": "Program Manager – Health & Safety / IPPF",
    "org": "جمعية خير وبركة والمرأة الجديدة",
    "gov": "الأسمرات",
    "type": "دوام كامل",
    "sec": "إدارة البرامج والصحة",
    "sal": "",
    "dl": "2026-10-08",
    "contact": "",
    "desc": "مدير برنامج للصحة والسلامة ضمن IPPF.",
    "link": "https://bit.ly/4yoqmzV",
    "source": "Khayr wa Baraka & New Woman Association"
  },
  {
    "title": "Business Development Sector",
    "org": "جمعية خير وبركة والمرأة الجديدة",
    "gov": "القاهرة",
    "type": "دوام كامل",
    "sec": "تطوير الأعمال",
    "sal": "",
    "dl": "2026-10-04",
    "contact": "",
    "desc": "فرصة ضمن قطاع تطوير الأعمال.",
    "link": "https://bit.ly/4jrNKaT",
    "source": "Khayr wa Baraka & New Woman Association"
  },
  {
    "title": "Social Media Specialist",
    "org": "Mersal",
    "gov": "المعادي – القاهرة",
    "type": "دوام كامل",
    "sec": "الإعلام والتواصل",
    "sal": "",
    "dl": "",
    "contact": "",
    "desc": "Social Media Specialist – Full Time / Hybrid.",
    "link": "https://wuzzuf.net/jobs/careers/Mersal-Egypt-45113",
    "source": "Wuzzuf / Mersal"
  },
  {
    "title": "Project Manager",
    "org": "مكتب التنمية الإيبارشي بالإسماعيلية – IDDO",
    "gov": "الإسماعيلية",
    "type": "دوام كامل",
    "sec": "إدارة المشاريع",
    "sal": "",
    "dl": "",
    "contact": "",
    "desc": "Project Manager – الإعلان حديث، وموعد الإغلاق غير ظاهر في المصدر المفهرس.",
    "link": "https://www.jobs-arab.com/eg/job-location/%D8%A7%D9%84%D8%A7%D8%B3%D9%85%D8%A7%D8%B9%D9%8A%D9%84%D9%8A%D9%87/",
    "source": "Jobs-Arab / IDDO"
  },
  {
    "title": "Accountant",
    "org": "مكتب التنمية الإيبارشي بالإسماعيلية – IDDO",
    "gov": "الإسماعيلية",
    "type": "دوام كامل",
    "sec": "الإدارة المالية",
    "sal": "",
    "dl": "",
    "contact": "",
    "desc": "Accountant – الإعلان حديث، وموعد الإغلاق غير ظاهر في المصدر المفهرس.",
    "link": "https://www.jobs-arab.com/eg/job-profession/%D9%85%D8%A7%D9%84-%D9%88%D9%85%D8%AD%D8%A7%D8%B3%D8%A8%D9%87/job-location/%D8%A7%D9%84%D8%A7%D8%B3%D9%85%D8%A7%D8%B9%D9%8A%D9%84%D9%8A%D9%87/",
    "source": "Jobs-Arab / IDDO"
  },
  {
    "title": "Director of Psychosocial Department",
    "org": "StARS",
    "gov": "القاهرة",
    "type": "دوام كامل",
    "sec": "الدعم النفسي والاجتماعي",
    "sal": "",
    "dl": "2026-10-03",
    "contact": "applications@stars-egypt.org",
    "desc": "مدير إدارة الدعم النفسي والاجتماعي.",
    "link": "https://stars-egypt.org/",
    "source": "StARS"
  },
  {
    "title": "Senior Public Relations Specialist",
    "org": "مؤسسة حياة كريمة",
    "gov": "القاهرة الجديدة",
    "type": "دوام كامل",
    "sec": "العلاقات العامة والاتصال",
    "sal": "",
    "dl": "2026-10-01",
    "contact": "",
    "desc": "علاقات عامة واتصالات خارجية مع زيارات ميدانية محتملة.",
    "link": "https://lnkd.in/ejSZ8i2k",
    "source": "Haya Karima Foundation"
  },
  {
    "title": "Senior CSR Specialist",
    "org": "مؤسسة حياة كريمة",
    "gov": "القاهرة الجديدة",
    "type": "دوام كامل",
    "sec": "المسؤولية المجتمعية والشراكات",
    "sal": "",
    "dl": "2026-10-01",
    "contact": "",
    "desc": "إدارة مبادرات المسؤولية المجتمعية والشراكات.",
    "link": "https://lnkd.in/eKmaF2ej",
    "source": "Haya Karima Foundation"
  },
  {
    "title": "Content & Digital Communications Senior Specialist",
    "org": "مؤسسة حياة كريمة",
    "gov": "القاهرة الجديدة",
    "type": "دوام كامل",
    "sec": "الإعلام والاتصال الرقمي",
    "sal": "",
    "dl": "2026-10-01",
    "contact": "",
    "desc": "المحتوى والاتصالات الرقمية وإدارة الحملات والمحتوى.",
    "link": "https://lnkd.in/eagS3in8",
    "source": "Haya Karima Foundation"
  },
  {
    "title": "Business Development Specialist",
    "org": "مؤسسة حياة كريمة",
    "gov": "القاهرة الجديدة",
    "type": "دوام كامل",
    "sec": "تطوير الأعمال والشراكات",
    "sal": "",
    "dl": "2026-10-01",
    "contact": "",
    "desc": "تطوير فرص وشراكات وتمويلات استراتيجية.",
    "link": "https://lnkd.in/ePMn7FYg",
    "source": "Haya Karima Foundation"
  },
  {
    "title": "MEAL Officer",
    "org": "مؤسسة حياة كريمة",
    "gov": "القاهرة الجديدة",
    "type": "دوام كامل",
    "sec": "المتابعة والتقييم والمساءلة والتعلم",
    "sal": "",
    "dl": "2026-10-01",
    "contact": "",
    "desc": "دعم أنظمة المتابعة وجودة البيانات وقياس الأداء.",
    "link": "https://lnkd.in/ey_6AhUJ",
    "source": "Haya Karima Foundation"
  },
  {
    "title": "Supply Chain Manager",
    "org": "مؤسسة حياة كريمة",
    "gov": "القاهرة الجديدة",
    "type": "دوام كامل",
    "sec": "المشتريات وسلاسل الإمداد",
    "sal": "",
    "dl": "2026-10-01",
    "contact": "",
    "desc": "
